version: "3"

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    ports:
      - 20051:10051
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - DB_SERVER_PORT=54320
      - ZBX_STARTTRAPPERS=0
      - ZBX_STARTJAVAPOLLERS=0
      - ZBX_CACHESIZE=128M
    depends_on:
      - postgres-server

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    ports:
      - "8081:8080"
      - "8443:8443"
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=20051
      - ZBX_SERVER_NAME=Zabbix本机开发环境
      - PHP_TZ=Asia/Shanghai
    depends_on:
      - postgres-server
      - zabbix-server

  postgres-server:
    image: postgres:15-alpine
    volumes:
      - pgsql_data_volume:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - 54320:5432
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
      - DB_SERVER_PORT=54320

volumes:
  pgsql_data_volume:
