# version: "3"

services:
  postgres-server:
    image: postgres:17-alpine
    restart: always
    volumes:
      - postgresql_data_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
      - DB_SERVER_PORT=5432

volumes:
  postgresql_data_volume:
