[book]
authors = ["李文军"]
language = "zh"
multilingual = false
src = "src"
title = "我的知识图谱"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
