version: "3"

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - server

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:secretpassword@db:5432/postgres
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
      PGRST_JWT_SECRET: 5rmZEf1uIYJj88VfEFPH3bMw9wvPfJL9
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - pgsql_data_volume:/var/lib/postgresql/data/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_DB: postgres
      # POSTGRES_USER: app_user
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  pgsql_data_volume:
